### ISSUE TITLE
Błąd w lab1

### ISSUE THREAD

**Issue by Carbon225** [apohllo/sztuczna-inteligencja#1]
## Wyszukiwanie hiperparametrów na siatce
```python
folds = KFold(n_splits=10, shuffle=True, random_state=0)
hyper_params = [{"n_features_to_select": list(range(1, train_data.shape[1]))}]
X = train_data_linear.drop(inplace=False, columns=["Age"]).drop(columns="Survived")
```
Napisane zostało, że najlepsze rozwiązanie dostajemy dla 8 cech zamiast 9.
Nie mamy jednak 9 cech tylko 8. W train_data_linear mamy 10 kolumn.
Jedna to `Survived` - usuwamy.
Druga to `Age` - też usuwamy bo to nasze $y$.
`range(1, train_data.shape[1])` - tutaj jest błąd.
Powinno być `range(1, X.shape[1] + 1)`, trzeba `X` dać linijkę wyżej.

**Comment by apohllo** [comment]
Laboratorium zostało zmienione i używamy nowych danych. Zamykam.
