### ISSUE TITLE
Lab4

### ISSUE THREAD

**Issue by bblachut** [apohllo/sztuczna-inteligencja#10]
W zadaniu 4 "image = image.to(device)" wyrzuca błąd, ponieważ metoda jest wywoływana na nd.array zamiast tensora.

**Comment by bblachut** [comment]
W zad 5 chyba brakuje komórki odpowiedzialnej za uczenie modelu? W tym momencie funkcja train_model i DataLoadery nie są nigdzie używane

**Comment by l0rd11** [comment]
zad 4. a tak powinno być image_tensor nie image, ten z wcześniejszej komórki.
zad 5. uczenie jest w zadaniu 6

**Comment by lubiluk** [comment]
To zostało napriawione kiedyś.
`image = torch.FloatTensor(image)`

**Comment by apohllo** [comment]
Ok. zamykamy
