### ISSUE TITLE
Lab4 - zadanie 7 - błędy w podanym kodzie obróbki

### ISSUE THREAD

**Issue by Y3drk** [apohllo/sztuczna-inteligencja#11]
w kodzie zadania podanym jako 'plug&play':   
    image = image.resize(**required_size**)
    **face_array** = np.asarray(image)   
    # change channel order from (H, W, C) to (C, H, W)
    face = np.moveaxis(face, 2, 0)  

1. metoda .resize() pobiera krotkę jako argument, podczas gdy tutaj mamy int zarówno jako wartość domyślną parametru, jak i wtedy gdy dostajemy kod odpalający tę funkcję (brak argumentu).  

2. Dodatkowo zmienna face_array nie jest nigdzie indziej użyta oprócz jej definicji, więc po co ona jest?  
Czy nie powinna się pojawić jako argument metody .moveaxis() ?

**Comment by l0rd11** [comment]
1.Tak racja, trochę za dużo przyciąłem przy zmianie nazwy na "required_size", powinno być jako krotka image.resize((required_size, required_size))
2. Też racja, najprościej zmienić nazwę z face_array na face, albo wstawić face_array jako argument w  np.moveaxis(face_array, 2, 0)

**Comment by Y3drk** [comment]
W zadaniu 8:

    if cosine_score <= thresh:
        print(">face is a Match - cosine (%.3f <= %.3f)" % (cosine_score, thresh))
        print(">face is a Match - euclidean (%.3f <= %.3f)" % (euclidean_score, euc_thresh))
    else:
        print(">face is NOT a Match (%.3f > %.3f)" % (cosine_score, thresh))
        print(">face is NOT a Match (%.3f > %.3f)" % (euclidean_score, euc_thresh))

Czemu uzależniamy wynik dla odległości euklidesowej od wyniku dla odległości cosinusowej?  
Wychodzą herezje (0.934 > 1.2)...
Proponuje fix:

    print("For cosine")
    if cosine_score <= thresh:
        print(">face is a Match - cosine (%.3f <= %.3f)" % (cosine_score, thresh))
    else:
        print(">face is NOT a Match (%.3f > %.3f)" % (cosine_score, thresh))
    
    print("For euclidean")
    if euclidean_score <= euc_thresh:
        print(">face is a Match - euclidean (%.3f <= %.3f)" % (euclidean_score, euc_thresh))
    else:
        print(">face is NOT a Match (%.3f > %.3f)" % (euclidean_score, euc_thresh))

**Comment by l0rd11** [comment]
wyniki powinny się zgadzać czyli jeżeli cosine_score > thresh to i euclidean_score > euc_thresh tak zostały dobrane threshold'y by na przykładowych zdjęciach się zgadzało i na ile testowałem to się zgadzało. Powstaje więc pytanie dla której pary zdjęć jest taki wynik?

sama propozycja jest oczywiście ok ale nie powinna być potrzebna.

**Comment by lubiluk** [comment]
Ta część została usunięta z notebooka.

**Comment by apohllo** [comment]
OK. Zamykamy.
