### ISSUE TITLE
Zad: 7 - usunąć wielokrotne losowanie

### ISSUE THREAD

**Issue by apohllo** [apohllo/sztuczna-inteligencja#14]
Gracz losowy losuje miejsce postawienia kółka/krzyżyka dla całej planszy. Ale jest funkcja `get_possible_moves` - można by losować indeks w tej tablicy co gwarantowałoby wylosowanie niezajętego miejsca.

**Comment by l0rd11** [comment]
pierwszy przykład miałbyć maksymalnie wprost bez dodatków i upiększeń taki młotek głupie nie głupie ale zawsze działa.  Funkcja get_possible_moves jest częścią przykładowego rozwiązania więc w zasadzie tu jej nie mamy.
