### ISSUE TITLE
Zad 7: rozważyć wprowadzenie funkcji heurystycznej

### ISSUE THREAD

**Issue by apohllo** [apohllo/sztuczna-inteligencja#15]
W instrukcji nie ma nic na ten temat, ale ewaluacja wartości dla algorytmu alfa/beta nie może opierać się wyłącznie na tym, że mamy wartości -1/0/1, bo wtedy nic ten algorytm nie może poprawić. Trzeba dodać informację np. o tym, żeby uzależnić wartość funkcji oceny od liczby ruchów potrzebnych do zakończenia gry.

**Comment by l0rd11** [comment]
jest to smaczek dla spostrzegawczych że lepsza funkcja ewaluacji by nam się przydała , ale i tak w tej postaci on poprawia działanie minmax. (można zerknąć na czas dzaiałania)

**Comment by apohllo** [comment]
Fakt, choć niektóre osoby w minimaksie dodały już taką optymalizację, że jak value = 1/-1, to kończ szukanie.
W każdym razie wydaje mi się, ze teraz minimaks i alfa-beta są do siebie bardzo podobne. W większości implementacji to parę linijek kodu więcej. A dodanie właśnie tej funkcji heurystycznej powodowałoby jednak większą różnicę pomiędzy tymi zadaniami.
