### ISSUE TITLE
Zad 7: rozważyć wprowadzenie np.array zamiast zwykłej tablicy

### ISSUE THREAD

**Issue by apohllo** [apohllo/sztuczna-inteligencja#16]
Wiele funkcji związanych z obliczaniem kto wygrał, jest realizowanych przez studentów w dość łopatologiczny sposób. Lepiej byłoby w tej grze promować wykorzystanie tablic z NumPy-a. Wtedy np. sprawdzenie, czy w danej linii jest wygrana, byłoby tożsame z policzeniem wartości bezwzględnej z sumy wartości w wierszu/kolumnie/diagonali.

**Comment by l0rd11** [comment]
to prawda, i nie jest to zły pomysł, tylko trochę zaciemnia istotę rzeczy a rozwiązanie łopatologiczne to uwypukla. I dla samego wyglądu kody bym to podmienił tyle że nie spodziewałbym się wzrostu użycia metod z numpy kto chciał to zrobić po prostu zrobił np.asarray.  Reszta i tak zrobi najprostszą możliwą opcje czy tam będzie lista, tablica numpy czy cokolwiek innego. Widziałem jak zamiast sum pisali pętle i to w stylu c. Więc rozumiem cel jednak nie spodziewałbym się jakiś specjalnie dużych efektów po tej zmianie.
