### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by lpawlak1** [apohllo/sztuczna-inteligencja#2]
Witam,
W laboratorium nr 1 w punkcie

`Trening ulepszonego modelu regresji`

mamy korzystać z `train_data` które już zdążyliśmy edytować. Więc próba znalezienia Nan w kolumnie Age mija się z celem. Gdyż całe Age jest średnią tej kolumny (zrobione wcześniej). Dalsza część ćwiczenia z takimi danymi jest bezcelowa :(

**Comment by apohllo** [comment]
Zgadzam się z @Zhylkaaa - w instrukcji jest napisane, że zmodyfikowane dane muszą być zapisane w innej zmiennej. Dlatego nie bardzo widzę, jak mielibyśmy poprawić laboratorium w tym punkcie.

**Comment by apohllo** [comment]
W sumie dostrzegam tutaj pewną subtelność - zamieniamy te dane średnią (w zmiennej `data2`), ale nigdzie potem ich nie wykorzystujemy. Może warto byłoby podkreślić, że chodzi tylko o wykonanie tej operacji, ale i tak dalej będziemy korzystać z oryginalnych danych? Że chodzi o przećwiczenie takiej prostej operacji.

**Comment by Y3drk** [comment]
> W sumie dostrzegam tutaj pewną subtelność - zamieniamy te dane średnią (w zmiennej `data2`), ale nigdzie potem ich nie wykorzystujemy. Może warto byłoby podkreślić, że chodzi tylko o wykonanie tej operacji, ale i tak dalej będziemy korzystać z oryginalnych danych? Że chodzi o przećwiczenie takiej prostej operacji.

Dokładnie tak, ja potem robiłem wszystko na data2, ponieważ byłem przekonany, że na coś nam się to przyda i dopiero bliżej końca się zorientowałem, że to nie było intencją.
