### ISSUE TITLE
Zad 4: distance/similarity w podobieństwie obrazów

### ISSUE THREAD

**Issue by apohllo** [apohllo/sztuczna-inteligencja#20]
Miara cos jest zazwyczaj wykorzystywana jako similarity, a Euclidean jako distance.
Może lepiej byłoby w zadaniu 8 użyć "naturalnych" interpretacji. 
Dodatkowo - euc_thresh nie jest do niczego wykorzystywany, więc po prostu można by odwrócić relację i użyć dla każdego "score" innej relacji (większe/mniejsze).

**Comment by lubiluk** [comment]
ta część została usunięta

**Comment by apohllo** [comment]
OK. Zamykamy.
