### ISSUE TITLE
Błędny wzór w lab1 na RMSE

### ISSUE THREAD

**Issue by Spontaniczny** [apohllo/sztuczna-inteligencja#24]
Wydaje mi się, że we wzorze na RMSE podanym w lab1 brakuje dzielenia przez n.

![obraz_2023-10-26_021858802](https://github.com/apohllo/sztuczna-inteligencja/assets/75948555/d45dd6c2-e86d-46dd-ac7d-9180a493d6de)

**Comment by apohllo** [comment]
Tak, zgadza się.

**Comment by apohllo** [comment]
Poprawione
