### ISSUE TITLE
Lab3 - błędny auroc w zad 4

### ISSUE THREAD

**Issue by dadamczykk** [apohllo/sztuczna-inteligencja#26]
W zadaniu 4 do obliczenia auroc używamy y_test i y_score, przy czym y_score nie jest zmieniane od zdefiniowania go w zadaniu 3, przez co auroc score wychodzi takie samo jak w zadaniu 3.
Wydaje mi się że zamiast y_score w funkcji roc_auc_score powinno być y_pred_test_score

**Comment by apohllo** [comment]
Poprawione.
