### ISSUE TITLE
Lab3: Błąd w funkcji `plot_precision_recall_curve`, może wystąpić dzielenie przez zero

### ISSUE THREAD

**Issue by mateon1** [apohllo/sztuczna-inteligencja#6]
Nie wiem jak to naprawić, ale dla wystarczająco złych modeli coś takiego się dzieje:
![PSI3-4-bug2](https://user-images.githubusercontent.com/1754784/203351059-239711f1-1132-4b87-af15-fed49c60d91b.png)

Wartości graniczne `y_pred_valid_score` wynoszą 0.2512 i 0.3776, więc nie dostały nam się tam żadne `nan`.

**Comment by Zhylkaaa** [comment]
miałeś szczęście jeśli tak można powiedzieć, bo dostałeś precision i recall zerowy, coś co mi nigdy nie zaszło :) 
wystarczyło zmienić argmax na nanargmax, bo jak się okazuje że `nan` jest wybierany przez argmax 🤷 
Mogę zamknąć issue?

**Comment by mateon1** [comment]
Potwierdzam że `nanargmax` naprawia problem z optimum.
I tak, przedostatnie elementy z `precision_recall_curve` mają i precision i recall równy zero.
![Screenshot_2022-11-22_18-09-09](https://user-images.githubusercontent.com/1754784/203377742-f63df8cf-ebb7-4f06-9eee-9a948e663226.png)

**Comment by Zhylkaaa** [comment]
Jeśli trening 'zapada' do jakiejś wartości to jest to możliwe, nie oczekiwałem że tu coś takiego może zajść, ale to jeszcze raz pokazuje ile problemów dostajemy kiedy mamy nie regularyzowaną sieć. Myślę że można to zamknąć
