### ISSUE TITLE
Lab3: Wiele problemów z sekcją "Akceleracja sprzętowa"

### ISSUE THREAD

**Issue by mateon1** [apohllo/sztuczna-inteligencja#7]
1. Model jest zbudowany bezpośrednio na podstawie `torch.nn.Sequential`, więc `predict_proba` nie jest zdefiniowane. Przy całkiem sensownej implementacji funkcji `evaluate_model` która korzysta z tej metody, zamiast ręcznie liczyć aktywacje, kod się psuje.
2. Kod korzysta z kluczy `"auroc"` i `"f1"`, których nie ma, mają być `"AUROC"` i `"F1-score"`.

**Comment by Zhylkaaa** [comment]
2 to nie tak wiele :) 
Sorry, po ostatnim refactorze ta sekcja nie została zmieniona. Dzięki za zwrócenie uwagi ❤️
